version: '3.9'
services:
  caddy:
    build: .
    env_file:
      - .env
    volumes:
      - data:/data
      - ./etc:/etc/caddy
      - ./svr:/svr
    # networks:
    #  - default
    # ports:
    #  - 80:80/tcp
    #  - 443:443/tcp
    #  - 443:443/udp
    network_mode: 'host'
    expose:
      - 80/tcp
      - 443/tcp
      - 443/udp
    logging:
      driver: syslog
      options:
        tag: caddy
    restart: always
networks:
  default:
volumes:
  data:
